// GENERATED by scripts/gen-manifest-types.mjs from schemas/manifest.v1.json — do not edit.
// Regenerate with `pnpm --filter dianome gen:types`.

export type Sha256 = string;

export type Config = {
  hidden_size: number;
  num_hidden_layers: number;
  num_attention_heads: number;
  num_key_value_heads: number;
  intermediate_size: number;
  vocab_size: number;
  rms_norm_eps: number;
  rope_theta: number;
  tie_word_embeddings: boolean;
  max_position_embeddings: number;
};

/** Where a contiguous run of an entry's bytes lives inside one physical chunk */
export type Segment = {
  chunk: Sha256;
  offset: number;
  length: number;
};

/** A sub-array of a quantized entry: offset relative to the entry start (256-byte aligned) and byte length */
export type Part = {
  offset: number;
  length: number;
};

export type Storage = {
  kind: "fp16";
} | {
  kind: "q8";
  parts: {
    weights: Part;
    scales: Part;
  };
} | {
  kind: "q4";
  group_size: 128;
  parts: {
    weights: Part;
    scales: Part;
    zeros: Part;
  };
};

export type Entry = {
  /** Original safetensors key (lm_head.weight when tied and absent from the file) */
  name: string;
  /** Position-independent role, e.g. attn.q_proj.weight, mlp.gate_proj.weight, input_layernorm.weight */
  role: string;
  shape: number[];
  storage: Storage;
  /** Ordered; the client concatenates. Starts at a 256-byte-aligned offset of the group stream. */
  segments: Segment[];
  /** The entry has no bytes of its own; its segments point into the embed group */
  tied?: true;
};

export type Group = {
  name: string;
  /** Sum of the listed chunks' lengths (0 when tied) */
  bytes: number;
  /** Ordered; download order for the group. Chunk boundaries restart at every group stream. */
  chunks: Sha256[];
  entries: Entry[];
  /** lm_head with tie_word_embeddings: no chunks of its own */
  tied?: true;
};

export type Variant = {
  /** Sum of group bytes */
  bytes: number;
  /** Fixed order: embed, layer.0 .. layer.L-1, final_norm, lm_head */
  groups: Group[];
};

/** A plain file stored as one stream (tokenizer files, or every file of a pack-dir artifact) */
export type File = {
  /** File name, or path relative to the packed directory */
  name: string;
  bytes: number;
  chunks: Sha256[];
  segments: Segment[];
};

/** Two-level manifest for a content-addressed chunk store. Physical layer: `chunks` (sha256 -> bytes). Logical layer: either `variants` (a safetensors model packed per layer group as fp16/q8/q4) or `files` (a directory of runtime-native files packed one stream per file). Every `bytes` field is a sum and must equal the sum of the listed chunks' lengths. */
export type ManifestBase = {
  schema: 1;
  /** Artifact id; manifests live at manifests/<id>/latest.json and manifests/<id>/<sha256>.json */
  id: string;
  source: {
    /** Hugging Face repo id, or a local:<name> marker for pack-dir on an unlabelled directory */
    repo: string;
    /** Hugging Face commit sha, or empty when unknown */
    revision: string;
  };
  /** config.model_type of the source, e.g. qwen2 */
  family?: string;
  config?: Config;
  tokenizer?: {
    files: File[];
  };
  /** Only for `files` manifests (generic packer) */
  runtime?: "webllm" | "transformersjs" | "other";
  chunk_size: 8388608;
  /** Global physical table. Key = lowercase hex sha256 of the chunk bytes, stored at chunks/<sha256>. */
  chunks: Record<string, {
    bytes: number;
  }>;
  /** At least one of fp16/q8/q4. fp16 was required until Phase 7, where 3B/7B are packed and uploaded as q8+q4 only (the split server loads fp16 from the HF cache). */
  variants?: {
    fp16?: Variant;
    q8?: Variant;
    q4?: Variant;
  };
  files?: File[];
};

/** Model manifest (pack-model) */
export type ModelManifest = ManifestBase & Required<Pick<ManifestBase, "family" | "config" | "tokenizer" | "variants">> & { files?: never; runtime?: never };

/** Runtime-native files manifest (pack-dir) */
export type FilesManifest = ManifestBase & Required<Pick<ManifestBase, "runtime" | "files">> & { variants?: never; config?: never; tokenizer?: never };

export type Manifest = ModelManifest | FilesManifest;
