// Generated by scripts/gen-privacy-band.mjs from server/probes/results; do not edit. Same content as data/privacy-band.qwen2.5-0.5b-instruct.json.
export const PRIVACY_BAND = {
  "model": "qwen2.5-0.5b-instruct",
  "source": "server/probes/results/band.json (linear 40k + inversion) and linear-500k.json (linear 500k); docs/phase-4-notes.md",
  "heldOut": {
    "repo": "Salesforce/wikitext",
    "config": "wikitext-103-raw-v1",
    "split": "test",
    "tokens": 50000,
    "heldOutTokens": 10240
  },
  "coverage500k": 0.9728,
  "coverage40k": 0.8202,
  "definition": "boundary i = the hidden state that leaves the client when N = i (the input to block i; 0 = token embeddings; L = the input to the final norm). top-1 = fraction of held-out positions whose input token a probe trained on that boundary recovers.",
  "rows": [
    {
      "boundary": 0,
      "linear500k_top1": 0.9727,
      "linear500k_top5": 0.9728,
      "linear_top1": 0.8162,
      "linear_top5": 0.8202,
      "inversion_top1": 0.8188,
      "inversion_top5": 0.8202,
      "nn_top1": 1
    },
    {
      "boundary": 1,
      "linear500k_top1": 0.9694,
      "linear500k_top5": 0.9714,
      "linear_top1": 0.8133,
      "linear_top5": 0.8188,
      "inversion_top1": 0.8002,
      "inversion_top5": 0.8144,
      "nn_top1": 0.0045
    },
    {
      "boundary": 2,
      "linear500k_top1": 0.9645,
      "linear500k_top5": 0.9705,
      "linear_top1": 0.8014,
      "linear_top5": 0.8153,
      "inversion_top1": 0.7813,
      "inversion_top5": 0.811,
      "nn_top1": 0.0007
    },
    {
      "boundary": 3,
      "linear500k_top1": 0.9563,
      "linear500k_top5": 0.9669,
      "linear_top1": 0.7835,
      "linear_top5": 0.8069,
      "inversion_top1": 0.7604,
      "inversion_top5": 0.7971,
      "nn_top1": 0.0003
    },
    {
      "boundary": 4,
      "linear500k_top1": 0.9443,
      "linear500k_top5": 0.9602,
      "linear_top1": 0.7673,
      "linear_top5": 0.8,
      "inversion_top1": 0.7433,
      "inversion_top5": 0.7882,
      "nn_top1": 0.0002
    },
    {
      "boundary": 5,
      "linear500k_top1": 0.9345,
      "linear500k_top5": 0.9546,
      "linear_top1": 0.7604,
      "linear_top5": 0.795,
      "inversion_top1": 0.7394,
      "inversion_top5": 0.7879,
      "nn_top1": 0.0002
    },
    {
      "boundary": 6,
      "linear500k_top1": 0.9175,
      "linear500k_top5": 0.9467,
      "linear_top1": 0.7309,
      "linear_top5": 0.7832,
      "inversion_top1": 0.7216,
      "inversion_top5": 0.7738,
      "nn_top1": 0.0003
    },
    {
      "boundary": 7,
      "linear500k_top1": 0.9071,
      "linear500k_top5": 0.9409,
      "linear_top1": 0.7215,
      "linear_top5": 0.7708,
      "inversion_top1": 0.7158,
      "inversion_top5": 0.7633,
      "nn_top1": 0
    },
    {
      "boundary": 8,
      "linear500k_top1": 0.899,
      "linear500k_top5": 0.9324,
      "linear_top1": 0.7054,
      "linear_top5": 0.7562,
      "inversion_top1": 0.7075,
      "inversion_top5": 0.7595,
      "nn_top1": 0.0001
    },
    {
      "boundary": 9,
      "linear500k_top1": 0.887,
      "linear500k_top5": 0.9271,
      "linear_top1": 0.6891,
      "linear_top5": 0.7438,
      "inversion_top1": 0.7036,
      "inversion_top5": 0.7523,
      "nn_top1": 0
    },
    {
      "boundary": 10,
      "linear500k_top1": 0.8779,
      "linear500k_top5": 0.919,
      "linear_top1": 0.6765,
      "linear_top5": 0.7362,
      "inversion_top1": 0.6973,
      "inversion_top5": 0.7502,
      "nn_top1": 0.0001
    },
    {
      "boundary": 11,
      "linear500k_top1": 0.8789,
      "linear500k_top5": 0.9188,
      "linear_top1": 0.6673,
      "linear_top5": 0.728,
      "inversion_top1": 0.6983,
      "inversion_top5": 0.7491,
      "nn_top1": 0
    },
    {
      "boundary": 12,
      "linear500k_top1": 0.8706,
      "linear500k_top5": 0.9126,
      "linear_top1": 0.6616,
      "linear_top5": 0.7234,
      "inversion_top1": 0.6958,
      "inversion_top5": 0.7472,
      "nn_top1": 0.0001
    },
    {
      "boundary": 13,
      "linear500k_top1": 0.8699,
      "linear500k_top5": 0.9147,
      "linear_top1": 0.6566,
      "linear_top5": 0.7203,
      "inversion_top1": 0.6932,
      "inversion_top5": 0.7453,
      "nn_top1": 0.0001
    },
    {
      "boundary": 14,
      "linear500k_top1": 0.866,
      "linear500k_top5": 0.9117,
      "linear_top1": 0.6576,
      "linear_top5": 0.7245,
      "inversion_top1": 0.6963,
      "inversion_top5": 0.7476,
      "nn_top1": 0
    },
    {
      "boundary": 15,
      "linear500k_top1": 0.8724,
      "linear500k_top5": 0.9173,
      "linear_top1": 0.6616,
      "linear_top5": 0.7288,
      "inversion_top1": 0.6901,
      "inversion_top5": 0.7464,
      "nn_top1": 0
    },
    {
      "boundary": 16,
      "linear500k_top1": 0.8754,
      "linear500k_top5": 0.9204,
      "linear_top1": 0.6672,
      "linear_top5": 0.7316,
      "inversion_top1": 0.6911,
      "inversion_top5": 0.7484,
      "nn_top1": 0.0002
    },
    {
      "boundary": 17,
      "linear500k_top1": 0.8823,
      "linear500k_top5": 0.9253,
      "linear_top1": 0.6885,
      "linear_top5": 0.7493,
      "inversion_top1": 0.6896,
      "inversion_top5": 0.7517,
      "nn_top1": 0.0001
    },
    {
      "boundary": 18,
      "linear500k_top1": 0.8715,
      "linear500k_top5": 0.9227,
      "linear_top1": 0.6819,
      "linear_top5": 0.7472,
      "inversion_top1": 0.6882,
      "inversion_top5": 0.749,
      "nn_top1": 0
    },
    {
      "boundary": 19,
      "linear500k_top1": 0.8712,
      "linear500k_top5": 0.9204,
      "linear_top1": 0.6763,
      "linear_top5": 0.7447,
      "inversion_top1": 0.685,
      "inversion_top5": 0.7471,
      "nn_top1": 0.0001
    },
    {
      "boundary": 20,
      "linear500k_top1": 0.8687,
      "linear500k_top5": 0.9209,
      "linear_top1": 0.6673,
      "linear_top5": 0.7388,
      "inversion_top1": 0.6797,
      "inversion_top5": 0.7463,
      "nn_top1": 0.0004
    },
    {
      "boundary": 21,
      "linear500k_top1": 0.8588,
      "linear500k_top5": 0.9178,
      "linear_top1": 0.6513,
      "linear_top5": 0.7331,
      "inversion_top1": 0.6636,
      "inversion_top5": 0.7443,
      "nn_top1": 0.0005
    },
    {
      "boundary": 22,
      "linear500k_top1": 0.8409,
      "linear500k_top5": 0.9076,
      "linear_top1": 0.6262,
      "linear_top5": 0.7153,
      "inversion_top1": 0.6432,
      "inversion_top5": 0.7251,
      "nn_top1": 0.0005
    },
    {
      "boundary": 23,
      "linear500k_top1": 0.8263,
      "linear500k_top5": 0.898,
      "linear_top1": 0.6117,
      "linear_top5": 0.707,
      "inversion_top1": 0.6156,
      "inversion_top5": 0.7107,
      "nn_top1": 0.0008
    },
    {
      "boundary": 24,
      "linear500k_top1": 0.7881,
      "linear500k_top5": 0.8682,
      "linear_top1": 0.5744,
      "linear_top5": 0.6783,
      "inversion_top1": 0.5607,
      "inversion_top5": 0.6609,
      "nn_top1": 0.0014
    }
  ]
} as const;
