// Generates docs/phase-5b-notes.md from measured results only:
//   packages/runtime/results/gates.json      gate 8 (lm_head) and gate 9 (local greedy) from gates.spec.ts
//   packages/sdk/results/split-e2e.json      run.spec.ts: fp16 mode gates, policy runs, telemetry rows
//   packages/sdk/results/split-measure.json  measure.spec.ts: planner inputs, choices per policy, N sweep, breakdowns
//   packages/sdk/results/split-browsers.json scripts/split-browsers.mjs: planner inputs on WebKit / Firefox / Chrome
//
//   node scripts/split-notes.mjs        (from packages/sdk)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { execSync } from "node:child_process";

const repo = resolve(import.meta.dirname, "../../..");
const rd = (p) => (existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : null);
const gates = rd(resolve(repo, "packages/runtime/results/gates.json"));
const e2e = rd("results/split-e2e.json"), meas = rd("results/split-measure.json"), browsers = rd("results/split-browsers.json");
const f = (x, d = 1) => (x === null || x === undefined || !Number.isFinite(Number(x)) ? "–" : Number(x).toFixed(d));
const e = (x, d = 2) => (x === 0 ? "0" : Number(x).toExponential(d));
const mib = (b) => (b / 2 ** 20).toFixed(0);
const commit = execSync("git rev-parse --short HEAD", { cwd: repo }).toString().trim();
const sdkSize = execSync("node scripts/size-check.mjs").toString().trim();
const runtimeDist = ["index", "tokenizer", "planner", "session", "protocol"].map((n) => { const p = resolve(repo, `packages/runtime/dist/${n}.js`); return existsSync(p) ? `${n}.js ${readFileSync(p).length} bytes` : `${n}.js (not built)`; }).join(", ") + " plus shared chunks (code-split; the subpath entries carry no WebGPU code)";
const median = (a) => { const s = [...a].sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : 0; };

let md = `# Phase 5b notes — split session, planner, run(), slider demo

Measured only. Sources: \`packages/runtime/results/gates.json\` (gates 8–9, \`gates.spec.ts\`), \`packages/sdk/results/split-e2e.json\`
(\`test/e2e-split/run.spec.ts\`), \`split-measure.json\` (\`measure.spec.ts\`), \`split-browsers.json\` (\`scripts/split-browsers.mjs\`);
regenerated by \`packages/sdk/scripts/split-notes.mjs\`. Tree at ${commit} (uncommitted working tree at generation time).
Servers for every browser run: \`dianome-server serve\` on this Mac (mps, \`SPLIT_TOKEN\` + \`SPLIT_SIGNING_KEY\`), \`wrangler dev\` for
the Worker (session tokens, rates, plan proxy, telemetry), the local chunk store on one static origin. The tunnel
(\`wss://split.dianome.dev\`) was not up during these runs, so every RTT below is loopback.

Hardware and browser: ${gates?.info ? `${gates.info.vendor} ${gates.info.architecture}` : "?"}; Google Chrome via Playwright \`channel: "chrome"\`, headless${e2e?.info ? ` (${e2e.info.ua.match(/Chrome\/[\d.]+/)?.[0] ?? ""})` : ""}.

`;

// -- gate 8 / 9
if (gates?.gate8) {
  md += `## lm_head gate (gate 8): every row of the runtime's final norm + lm_head vs \`logits.npy\`

fp16 is the gate (rel RMS < 1e-2, argmax identical on all 32 rows); q8/q4 use the q8 embed table as the tied head and are
compared with the same fp16 logits, so their rows record the whole quantised model's deviation, not the head's.

| variant | head kernel | rel RMS | max abs | argmax mismatches (rows) | last-row top-2 | lm_head + readback ms (5 runs) |
|---|---|---|---|---|---|---|
`;
  for (const r of gates.gate8) md += `| ${r.variant} | ${r.headMatvec} | ${e(r.cmp.relRms, 3)} | ${e(r.cmp.maxAbs, 3)} | ${r.argmaxMismatches.length === 0 ? "none" : r.argmaxMismatches.map((m) => m.row).join(" ")} | ${r.lastRowTop2.map((t) => `${t.id} (${f(t.logit, 3)})`).join(", ")} | ${r.lmHeadMs.map((x) => f(x, 2)).join(" ")} |\n`;
  md += `\n`;
}
if (gates?.gate9) {
  md += `## Local-mode gate (gate 9): 16 greedy tokens, lm_head + sampler in the runtime, no server

Free-running (each sampled token is fed back). fp16 reference: \`greedy.json\` (full model); q8/q4 reference: \`<variant>/greedy.json\`
\`local\` (PyTorch with every block and the embedding dequantised and lm_head tied to the dequantised embedding).

| variant | tokens | reference | mismatches | decode medians: client / lm_head / sampling / total ms |
|---|---|---|---|---|
`;
  for (const r of gates.gate9) { const m = (k) => median(r.steps.slice(1).map((s) => s[k])); md += `| ${r.variant} | ${r.tokens.join(" ")} | ${r.expected.join(" ")} | ${r.mismatches.length ? JSON.stringify(r.mismatches) : "none"} | ${f(m("clientMs"), 2)} / ${f(m("lmHeadMs"), 2)} / ${f(m("sampleMs"), 2)} / ${f(m("totalMs"), 2)} |\n`; }
  md += `\n`;
}

// -- planner inputs
if (meas?.inputs) {
  const i = meas.inputs;
  md += `## Planner inputs on this Mac (Chrome; \`run()\` measured them, q4, maxCtx 1024)

| input | value |
|---|---|
| WebGPU / maxBufferSize | ${i.device.webgpu} / ${mib(i.device.maxBufferSize)} MiB |
| storage quota → GPU budget | ${i.device.quotaBytes ? mib(i.device.quotaBytes) + " MiB" : "not reported"} → ${mib(i.device.gpuBudgetBytes)} MiB (min(cap 2 GiB, max(1 GiB, quota / 2))) |
| microbench ms/block T=1 / T=32 | ${f(i.device.msPerBlockT1, 3)} / ${f(i.device.msPerBlockT32, 3)} |
| microbench lm_head + readback / export ms | ${f(i.device.lmHeadMs, 2)} / ${f(i.device.exportMs, 2)} |
| cached | ${i.device.embedCached ? "embed + " : ""}${i.device.cachedBlocks} blocks (cache: "none" in the harness) |
| download bandwidth (1 MB probe) | ${i.network.bytesPerSecond ? (i.network.bytesPerSecond / 1e6).toFixed(0) + " MB/s (loopback)" : "unknown"} |
| RTT (WS ping, median of 5) | ${f(i.network.rttMs, 2)} ms (loopback) |
| server /plan | L ${i.server?.L}, busy ${f(i.server?.busyFraction60s, 3)}, ms/block decode ${f(i.server?.msPerBlockDecode, 3)} prefill ${f(i.server?.msPerBlockPrefill, 3)}, lm_head ${f(i.server?.lmHeadMs, 2)} ms, device ${i.server?.device} |
| rate | ${i.rate ? (i.rate.usdPerHour === null ? `none (rates.json usd_per_hour null; gpu "${i.rate.gpu}", retrieved ${i.rate.retrieved}) → shares only` : `${i.rate.gpu} $${i.rate.usdPerHour}/h (${i.rate.retrieved})`) : "not fetched"} |
| model | ${i.model.variant}: ${mib(i.model.blockBytes[0])} MiB/block, embed ${mib(i.model.embedBytes)} MiB, head GPU ${mib(i.model.lmHeadGpuBytes)} MiB, KV/block ${(i.model.kvBytesPerBlock / 2 ** 20).toFixed(2)} MiB, workspace ${mib(i.model.workspaceBytes)} MiB, cost floor ${i.model.serverCostFloor} |

`;
}
if (browsers) {
  md += `## Planner inputs on other browsers (\`scripts/split-browsers.mjs\`, prefer cost, q4, fresh microbench)

| browser | WebGPU | ms/block T=1 / T=32 | lm_head / export ms | RTT ms | budget MiB | choice | outcome |
|---|---|---|---|---|---|---|---|
`;
  for (const [name, r] of Object.entries(browsers)) {
    if (name === "updated") continue;
    const d = r.plan?.inputs?.device, n = r.plan?.inputs?.network;
    md += `| ${name} ${r.version} | ${r.info?.webgpu ?? "?"}${d ? ` (planner: ${d.webgpu})` : ""} | ${d ? `${f(d.msPerBlockT1, 3)} / ${f(d.msPerBlockT32, 3)}` : "–"} | ${d ? `${f(d.lmHeadMs, 2)} / ${f(d.exportMs, 2)}` : "–"} | ${n ? f(n.rttMs, 2) : "–"} | ${d ? mib(d.gpuBudgetBytes) : "–"} | ${r.plan ? `${r.plan.mode} N=${r.plan.N} (est ${f(r.plan.estimate, 1)} ms)` : "–"} | ${r.error ? `error: ${r.error}` : r.plan ? r.plan.reasons.join("; ") : ""}${r.errors?.length ? ` page errors: ${r.errors.join(" / ")}` : ""} |\n`;
  }
  md += `\n`;
}

// -- policies
if (meas?.plans) {
  md += `## Planner choices per policy (same inputs)

| policy | choice | estimated ms/token | why |
|---|---|---|---|
`;
  for (const [p, r] of Object.entries(meas.plans)) md += `| ${p} | ${r.mode} N=${r.N} | ${f(r.estimate, 1)} | ${r.reasons.join("; ")} |\n`;
  md += `\n`;
}

// -- sweep
if (meas?.sweep) {
  md += `## Estimated vs measured ms/token, q4, N ∈ {0, 4, 8, 12, 16, 20, 24, local}

32-token fixture prompt, 32 new tokens, greedy, three runs per row; "measured" is the median decode step of the median run
(runtime prefill/decode + export + round trip + lm_head + sampling, wall clock in the page); the breakdown columns are
per-step medians of that run. network = round trip − server busy_ms. Estimates are the planner's for the same inputs.

| N | mode | est ms/token | measured (3 runs) | measured / est | client | export | network | server busy | lm_head | sampling | prefill est / measured ms | server share | linear-500k / inversion top-1 | load ms |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
`;
  const cands = meas.plans?.cost?.candidates ?? [];
  for (const r of meas.sweep) {
    const c = cands.find((x) => (r.mode === "local" ? x.mode === "local" : x.mode !== "local" && x.N === r.N));
    const b = r.breakdownMeasured;
    md += `| ${r.sel} | ${r.mode} | ${f(r.estimate, 2)} | ${f(r.measured, 2)} (${r.measuredRuns.map((x) => f(x, 2)).join(" / ")}) | ${r.estimate ? f(r.measured / r.estimate, 2) : "–"} | ${f(b.clientMs, 2)} | ${f(b.exportMs, 2)} | ${f(b.networkMs, 2)} | ${f(b.serverBusyMs, 2)} | ${f(b.lmHeadMs, 2)} | ${f(b.sampleMs, 2)} | ${f(r.prefillEstimate, 1)} / ${f(r.prefillMeasured, 1)} | ${c ? (c.serverShare * 100).toFixed(0) + "%" : "–"} | ${c?.privacy ? `${(c.privacy.linear500kTop1 * 100).toFixed(1)} / ${(c.privacy.inversionTop1 * 100).toFixed(1)}` : c?.mode === "local" ? "nothing sent" : "–"} | ${r.N === 0 ? "–" : r.loadMs === null ? "reused" : f(r.loadMs, 0)} |\n`;
  }
  md += `\nEstimate terms: client ms/block(T=1) × N + export + rtt + server ms/block × (L − N) + server lm_head (split/server);
client ms/block × N + client lm_head + sampling (local). Costs are shares only while \`bench/rates.json\` has no rate.\n\n`;
}

// -- fp16 gates via run() and policy runs
if (e2e?.fp16Gates) {
  const g = e2e.fp16Gates;
  md += `## run() mode gates (fp16, fixture prompt, 16 greedy tokens vs the full-model greedy)

| mode | N | tokens | tok/s (decode) | server busy_ms | load ms |
|---|---|---|---|---|---|
`;
  for (const [k, r] of Object.entries(g)) md += `| ${k} | ${r.N} | ${r.tokens.join(" ")} | ${f(r.tokPerS, 1)} | ${f(r.serverBusyMs, 1)} | ${r.N === 0 ? "–" : r.loadMs === null || r.loadMs === undefined ? "reused" : f(r.loadMs, 0)} |\n`;
  md += `\nAll three equal \`greedy.json\`: 752 83951 1526 279 57267 6176 13638 13 576 33581 374 264 6233 1992 11 448. The split row's N is the
planner's max feasible N under a 900 MiB GPU budget (local needs the 272 MiB fp16 head on top).\n\n`;
}
if (e2e?.policies) {
  md += `## run() with a policy (q4, chat template, session token minted by the Worker)

| policy | choice | why | tokens | tok/s | est ms/token | rtt ms | telemetry |
|---|---|---|---|---|---|---|---|
`;
  for (const [p, r] of Object.entries(e2e.policies)) md += `| ${p} | ${r.mode} N=${r.N} | ${r.reasons.join("; ")} | ${r.tokens} | ${f(r.tokPerS, 1)} | ${f(r.estimate, 1)} | ${f(r.rtt, 2)} | ${r.status} |\n`;
  md += `\n### The v3 telemetry row as written (\`POST /v1/telemetry/load\`, accepted by wrangler dev with 202)\n\n\`\`\`json\n${JSON.stringify(e2e.policies.cost?.report ?? e2e.telemetryPosted?.[0]?.body, null, 2)}\n\`\`\`\n\n`;
}

md += `## Package sizes

\`node scripts/size-check.mjs\` in packages/sdk (the main entry gained the lazy \`run\` / \`planRun\` stubs and an internal store accessor; Phase 5a: 44111 bytes / 14040 gzipped):

\`\`\`
${sdkSize}
\`\`\`

\`pnpm --filter dianome-runtime build\`: ${runtimeDist}.
`;

writeFileSync(resolve(repo, "docs/phase-5b-notes.md"), md);
console.log(`wrote docs/phase-5b-notes.md (${md.length} chars)`);
