#!/usr/bin/env node
// Generates docs/phase-7-notes.md (Phase 7 Part A3) from the results files only:
//   server/bench/results/l4/ingest-*.json, upload-*.json, cuda-*-<date>.json, timing.json
//   server/probes/results/l4/linear-*.json (+ server/probes/results/linear-500k.json for the 0.5B band)
//   packages/sdk/results/remote-l4.json
// The billing total, region and client location are the only hand-entered facts (BILLING below, pasted by Theo).
//   node scripts/phase7-notes.mjs
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const repo = resolve(dirname(new URL(import.meta.url).pathname), "..");
const J = (p) => JSON.parse(readFileSync(join(repo, p), "utf8"));
const BENCH = "server/bench/results/l4", PROBES = "server/probes/results/l4";
const BILLING = { total_usd: 1.51, balance_before: 10.0, balance_after: 8.49, explorer_usd: 1.049, explorer_note: "billing explorer, data one hour behind at the time", region: "RunPod EU-RO-1 (Secure Cloud, on-demand)", client: "this MacBook (Apple M4, 16 GB) in Houston, Google Chrome via Playwright, headless" };
const MODELS = ["qwen2.5-0.5b-instruct", "qwen2.5-3b-instruct", "qwen2.5-7b-instruct"];
const short = (m) => m.replace("qwen2.5-", "").replace("-instruct", "").toUpperCase();

const f = (n, d = 1) => (n === null || n === undefined || !Number.isFinite(n) ? "–" : n.toFixed(d));
const int = (n) => (Number.isFinite(n) ? Math.round(n).toLocaleString("en-US") : "–");
const mib = (b) => (b / 2 ** 20).toFixed(1);
const gib = (b) => (b / 2 ** 30).toFixed(2);
const median = (a) => { const s = [...a].filter((x) => Number.isFinite(x)).sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : NaN; };
const table = (headers, rows) => ["| " + headers.join(" | ") + " |", "|" + headers.map(() => "---").join("|") + "|", ...rows.map((r) => "| " + r.join(" | ") + " |")].join("\n");

const out = [];
const H = (s) => out.push(`\n## ${s}\n`);
const P = (s) => out.push(s + "\n");

// -- sources -------------------------------------------------------------------------------------------------------------
const benchFiles = Object.fromEntries(MODELS.map((m) => [m, readdirSync(join(repo, BENCH)).find((fn) => fn.startsWith(`cuda-${m}-`) && fn.endsWith(".json"))]));
const bench = Object.fromEntries(MODELS.map((m) => [m, J(`${BENCH}/${benchFiles[m]}`)]));
const timing = J(`${BENCH}/timing.json`);
const remote = J("packages/sdk/results/remote-l4.json");
const rate = bench[MODELS[0]].rates;

out.push(`# Phase 7 notes — L4 benchmarks, 3B privacy band, remote split

Generated by \`scripts/phase7-notes.mjs\` from the results files named in each section; nothing below is typed by hand
except the billing line and the two locations. Pod: **${rate.gpu}** at **$${rate.usd_per_hour}/h** (${rate.source}, retrieved
${rate.retrieved}), ${BILLING.region}; torch ${bench[MODELS[0]].versions.torch}, transformers ${bench[MODELS[0]].versions.transformers}.
Client for the remote runs: ${BILLING.client}. Pod scripts: \`scripts/pod/setup.sh\`, \`scripts/pod/run-all.sh\`
(\`server/bench/results/l4/logs/\` holds the run log, gitignored). Bench and probe dates: ${bench[MODELS[0]].date}.
`);

// -- ingest ------------------------------------------------------------------------------------------------------------
H("Ingest: 3B and 7B as q8 + q4");
P("`dianome-ingest pack-model --variants q8,q4` on the pod, then `inspect --json` and `upload --json` (fp16 is not packed or uploaded: the split server loads fp16 from the HF cache). Files: `server/bench/results/l4/ingest-<id>.json`, `upload-<id>.json`.");
const ingestRows = [];
for (const m of MODELS.slice(1)) {
  const i = J(`${BENCH}/ingest-${m}.json`), u = J(`${BENCH}/upload-${m}.json`);
  for (const v of ["q8", "q4"]) ingestRows.push([short(m), i.layers, i.tied ? "yes" : "no", v, int(i.variants[v].bytes), gib(i.variants[v].bytes), i.variants[v].chunks_listed, i.variants[v].chunks_unique]);
  ingestRows.push([short(m), "", "", "unique (q8 ∪ q4 + tokenizer)", int(i.unique_bytes), gib(i.unique_bytes), i.unique_chunks, `dedup saved ${mib(i.dedup.bytes_saved)} MiB (${i.dedup.shared_chunks} shared chunks)`]);
  ingestRows.push([short(m), "", "", "uploaded to R2", int(u.bytes_uploaded), gib(u.bytes_uploaded), `${u.uploaded} put, ${u.skipped} skipped`, `${u.wall_seconds} s; manifest ${u.manifest_sha256.slice(0, 12)}…`]);
}
P(table(["model", "L", "tied", "variant / row", "bytes", "GiB", "chunks listed", "chunks unique / note"], ingestRows));
const ing3 = J(`${BENCH}/ingest-qwen2.5-3b-instruct.json`), ing7 = J(`${BENCH}/ingest-qwen2.5-7b-instruct.json`);
P(`Sources: \`Qwen/Qwen2.5-3B-Instruct\` @ \`${ing3.source.revision}\`, \`Qwen/Qwen2.5-7B-Instruct\` @ \`${ing7.source.revision}\`; git ${ing3.git_commit.slice(0, 7)}. The bucket now holds ${gib(ing3.unique_bytes + ing7.unique_bytes)} GiB more than before the run (3B + 7B unique bytes), past the R2 free tier's 10 GB.`);

// -- cost curves ---------------------------------------------------------------------------------------------------------
for (const m of MODELS) {
  const b = bench[m];
  H(`Cost curve: ${short(m)}`);
  P(`\`dianome-server bench --model ${m} --device cuda --splits auto --gen-tokens ${b.gen_tokens} --runs ${b.runs} --require-rate\` → \`${BENCH}/${benchFiles[m]}\` (csv and md next to it). Device ${b.device}; ${b.rows[0].prompt_tokens} prompt tokens over 8 prompts, prefill + ${b.gen_tokens} greedy decode steps each, ${b.runs} runs, median; server busy time only. cost_per_1M_tokens = gpu_seconds_per_token × 1e6 × ${rate.usd_per_hour} / 3600.`);
  P(table(["N", "prompt_tokens", "gen_tokens", "busy_seconds", "gpu_seconds_per_token", "ms/token", "prefill_s", "decode ms/token", "cost_per_1M_tokens ($)", "cost(N)/cost(0)"],
    b.rows.map((r) => [r.N, r.prompt_tokens, r.gen_tokens, f(r.busy_seconds, 3), f(r.gpu_seconds_per_token, 6), f(r.gpu_seconds_per_token * 1e3, 3), f(r.prefill_seconds, 3), f(r.decode_seconds_per_token * 1e3, 3), f(r.cost_per_1M_tokens, 3), f(r.ratio_vs_N0, 3)])));
}

// -- cost summary with N* from the remote runs -----------------------------------------------------------------------------
H("Cost summary: the three curves, the floor, and N* under prefer: cost");
const nstar = {
  "qwen2.5-0.5b-instruct": { label: "local (Phase 5b and the Part B summariser on the Mac: prefer cost chose local every time)", N: null, share: 0 },
};
for (const m of MODELS.slice(1)) {
  const e = remote[m]; const costRuns = (e?.runs ?? []).filter((r) => !r.error && r.webgpu && r.policy === "cost");
  const last = costRuns.at(-1);
  nstar[m] = last ? { label: last.mode === "local" ? `local (N = ${last.N})` : `${last.mode} N = ${last.N}`, N: last.mode === "local" ? null : last.N, share: last.serverShare, mode: last.mode } : { label: "no remote run", N: null, share: NaN };
}
const summaryRows = MODELS.map((m) => {
  const b = bench[m], r0 = b.rows[0], rL = b.rows.at(-1), ns = nstar[m];
  const rowAt = ns.N === null ? null : b.rows.find((r) => r.N === ns.N);
  const costStar = ns.mode === "local" || ns.N === null && ns.share === 0 ? 0 : rowAt ? rowAt.cost_per_1M_tokens : NaN;
  const ratioStar = ns.mode === "local" || ns.N === null && ns.share === 0 ? 0 : rowAt ? rowAt.ratio_vs_N0 : NaN;
  return [short(m), b.rows[0] && rL.N, f(r0.gpu_seconds_per_token * 1e3, 2), f(r0.cost_per_1M_tokens, 2), f(rL.ratio_vs_N0, 3), f(rL.cost_per_1M_tokens, 2), ns.label, rowAt ? `${f(rowAt.gpu_seconds_per_token * 1e3, 2)} ms → $${f(costStar, 2)}` : ns.share === 0 ? "0 ms → $0.00" : "–", f(ratioStar, 3)];
});
P("N* is what the planner chose under `prefer: \"cost\"` on the client in the remote runs below (3B, 7B) and on the Mac (0.5B); its cost is read off that model's curve at N* (the bench's own measurement, not the remote run's).");
P(table(["model", "L", "ms/token at N = 0", "$/1M at N = 0", "cost(L)/cost(0) (the head floor)", "$/1M at N = L", "N* (prefer: cost)", "server ms/token → $/1M at N*", "cost(N*)/cost(0)"], summaryRows));

// -- privacy band --------------------------------------------------------------------------------------------------------
H("Privacy band: 3B beside 0.5B");
const l3 = J(`${PROBES}/linear-qwen2.5-3b-instruct.json`);
const l05 = J("server/probes/results/linear-500k.json");
P(`3B: \`dianome-server collect --tokens 50000\` then \`linear-probe --train-tokens 200000\` on the pod → \`${PROBES}/linear-qwen2.5-3b-instruct.json\`; training set ${l3.train_meta.n_documents} documents, ${int(l3.train_meta.n_tokens)} tokens from the WikiText-103 train split (seed ${l3.train_meta.sample_seed}, ${l3.train_meta.excluded_test_titles} test titles excluded); held-out set the same ${int(l3.coverage.val_tokens)} tokens as Phase 4 (${l3.test_meta.split.val_docs.length} documents of the test split); coverage ${f(l3.coverage.coverage, 4)} (${int(l3.coverage.val_tokens_seen_in_train)}/${int(l3.coverage.val_tokens)} held-out tokens have a type in the training set; ${l3.coverage.train_types} training types). Linear probe: AdamW, batch ${l3.linear_kw.batch}, up to ${l3.linear_kw.max_epochs} epochs, patience 1; device ${l3.device}; wall ${f(l3.wall_seconds, 0)} s. 0.5B: \`server/probes/results/linear-500k.json\` (Phase 4, 500k training tokens, coverage ${f(l05.coverage.coverage, 4)}). norm = linear / coverage. Boundaries are absolute (i = the input to block i; i = L is the input to the final norm), so the two columns line up by depth only at 0 and by fraction of L elsewhere.`);
const rows3 = [...l3.rows].sort((a, b) => a.boundary - b.boundary), rows05 = [...l05.rows].sort((a, b) => a.boundary - b.boundary);
const maxB = Math.max(rows3.length, rows05.length);
const bandRows = [];
for (let i = 0; i < maxB; i++) {
  const a = rows05[i], b = rows3[i];
  bandRows.push([i, a ? f(a.linear_top1, 4) : "", a ? f(a.linear_top5, 4) : "", a ? f(a.norm_top1, 4) : "", b ? f(b.linear_top1, 4) : "", b ? f(b.linear_top5, 4) : "", b ? f(b.norm_top1, 4) : "", b ? `${b.linear_epochs} / ${f(b.linear_train_seconds, 0)}` : ""]);
}
P(table(["boundary", "0.5B linear top-1 (500k)", "0.5B top-5", "0.5B norm top-1", "3B linear top-1 (200k)", "3B top-5", "3B norm top-1", "3B epochs / s"], bandRows));
const at = (rows, i) => rows.find((r) => r.boundary === i);
const L05 = rows05.length - 1, L3 = rows3.length - 1;
P("Same rows at the same fraction of depth (0, L/2, L):");
P(table(["model", "coverage", "boundary 0 raw / norm", "L/2 raw / norm", "L raw / norm"], [
  ["0.5B (L = 24, 500k)", f(l05.coverage.coverage, 4), `${f(at(rows05, 0).linear_top1, 3)} / ${f(at(rows05, 0).norm_top1, 3)}`, `${f(at(rows05, L05 / 2).linear_top1, 3)} / ${f(at(rows05, L05 / 2).norm_top1, 3)}`, `${f(at(rows05, L05).linear_top1, 3)} / ${f(at(rows05, L05).norm_top1, 3)}`],
  ["3B (L = 36, 200k)", f(l3.coverage.coverage, 4), `${f(at(rows3, 0).linear_top1, 3)} / ${f(at(rows3, 0).norm_top1, 3)}`, `${f(at(rows3, L3 / 2).linear_top1, 3)} / ${f(at(rows3, L3 / 2).norm_top1, 3)}`, `${f(at(rows3, L3).linear_top1, 3)} / ${f(at(rows3, L3).norm_top1, 3)}`],
]));

H("7B probes: not run");
const l7 = J(`${PROBES}/linear-qwen2.5-7b-instruct.json`);
P(`\`${PROBES}/linear-qwen2.5-7b-instruct.json\` records \`not_run: true\`: "${l7.reason}" (elapsed ${int(l7.elapsed_seconds)} s of a ${int(l7.budget_seconds)} s budget when the rule was evaluated on ${l7.date}; \`FORCE_7B_PROBES=1\` was not set). Inversion decoders were not run on the L4 for any model: on 0.5B they were within a few points of the linear probe at every boundary (Phase 4 notes).`);

// -- remote split --------------------------------------------------------------------------------------------------------
const remoteCols = ["mode / N", "runs", "tok/s", "step ms measured / est", "client", "export", "network", "server busy", "lm_head", "RTT ms", "bandwidth probe MB/s", "busy total ms", "server share", "$/1M planner", "$/1M from busy", "prefill ms measured / est", "load", "cache"];
function remoteRows(runs) {
  const groups = new Map();
  for (const r of runs.filter((r) => !r.error)) { const k = `${r.mode}/${r.N}`; if (!groups.has(k)) groups.set(k, []); groups.get(k).push(r); }
  const rows = [];
  for (const [k, g] of groups) {
    const m = (fn) => median(g.map(fn));
    const loads = g.filter((r) => r.load);
    const busyPerTok = m((r) => r.breakdown.server);
    rows.push([k === `local/${g[0].L}` ? `local (N = ${g[0].N})` : k.replace("/", " N = "), g.length, f(m((r) => r.tokPerS), 2), `${f(m((r) => r.measuredMsPerToken))} / ${f(m((r) => r.estimatedMsPerToken))}`,
      f(m((r) => r.breakdown.client)), f(m((r) => r.breakdown.export)), f(m((r) => r.breakdown.network)), f(busyPerTok), f(m((r) => r.breakdown.lm_head)),
      f(m((r) => r.rttMs)), f(m((r) => r.plannerInputs?.network?.bytesPerSecond / 1e6)), f(m((r) => r.serverBusyMs), 0), f(m((r) => r.serverShare), 3), f(m((r) => r.costPer1M), 2),
      f((busyPerTok / 1000) * 1e6 * rate.usd_per_hour / 3600, 2), `${f(m((r) => r.prefillMs), 0)} / ${f(m((r) => r.prefillEstMs), 0)}`,
      loads.length ? `${mib(median(loads.map((r) => r.load.bytes)))} MiB in ${f(median(loads.map((r) => r.load.ms)) / 1000)} s` : "runtime reused", g[0].cacheMode ?? "–"]);
  }
  return rows;
}
for (const m of ["qwen2.5-7b-instruct", "qwen2.5-3b-instruct"]) {
  const e = remote[m];
  if (!e) continue;
  H(`Remote split: ${short(m)}`);
  const good = e.runs.filter((r) => r.webgpu);
  const pc = e.plan_check;
  const ok = good.filter((r) => !r.error);
  P(`\`node scripts/measure-remote.mjs --model ${m}\` against \`${e.page}\` with the pod behind \`${pc.url}\` (server ${pc.model} L=${pc.L} on ${pc.device}, its own microbench ${f(pc.ms_per_block_decode, 3)} ms/block decode, ${f(pc.ms_per_block_prefill, 3)} prefill, lm_head ${f(pc.lm_head_ms, 2)} ms). Client ${e.client.browser} ${e.client.version} ${e.client.headless ? "headless" : "headed"}, ${e.client.adapter?.vendor}/${e.client.adapter?.architecture}, ${e.client.launchArgs?.join(" ")}. ${ok[0]?.promptTokens ?? "?"}-token chat prompt, ${ok[0]?.tokens ?? "?"} new tokens, greedy, q4; policy prefer cost then prefer server, 3 runs each; rows group runs by mode and N (medians within a group; "load" is the first run of that configuration). Client ms/block T=1 ${f(ok[0]?.plannerInputs?.device?.msPerBlockT1, 3)}, GPU budget ${ok.map((r) => mib(r.plannerInputs?.device?.gpuBudgetBytes ?? 0)).filter((v, i, a) => a.indexOf(v) === i).join(" → ")} MiB across runs (storage-quota derived). "$/1M from busy" = server busy ms per token × 1e6 × ${rate.usd_per_hour} / 3600 / 1000. File: \`packages/sdk/results/remote-l4.json\`.`);
  P(table(remoteCols, remoteRows(good)));
  const perRun = ok.map((r) => [r.policy, r.run, `${r.mode} N = ${r.N}`, f(r.tokPerS, 2), f(r.measuredMsPerToken), f(r.rttMs), f(r.plannerInputs?.network?.bytesPerSecond / 1e6), f(r.serverBusyMs, 0), r.reasons?.[0] ?? ""]);
  P("Every run (policy, run, choice, tok/s, step ms, RTT, bandwidth probe, busy total, first planner reason):");
  P(table(["policy", "run", "choice", "tok/s", "step ms", "RTT ms", "bw MB/s", "busy ms", "reason"], perRun));
  const bad = e.runs.filter((r) => !r.webgpu);
  if (bad.length) {
    H(`Remote split: the ${bad.length} earlier ${short(m)} runs without WebGPU`);
    P(`Kept on record, labelled \`webgpu: false\` in the results file: ${e.note ?? ""} They are all server N = 0, so they double as a repeat of the N = 0 row above under the older SDK build.`);
    P(table(remoteCols, remoteRows(bad)));
  }
}

// -- GPU time ------------------------------------------------------------------------------------------------------------
H("GPU time and the cost of the day");
P(`\`${BENCH}/timing.json\`, written by \`scripts/pod/run-all.sh\` after every step:`);
P(table(["step", "seconds", "minutes", "started", "finished"], Object.entries(timing.steps).map(([k, v]) => [k, v.seconds, f(v.seconds / 60, 1), v.started, v.finished])));
P(`Total in run-all.sh: ${int(timing.total_seconds)} s = ${f(timing.total_seconds / 3600, 2)} h of pod time under the script (setup, model downloads, the A2 serving hours and the idle time around them are not in this file). Billing, pasted from RunPod: **$${BILLING.total_usd.toFixed(2)}** for the day (balance $${BILLING.balance_before.toFixed(2)} → $${BILLING.balance_after.toFixed(2)}; the ${BILLING.explorer_note} showed $${BILLING.explorer_usd}). At $${rate.usd_per_hour}/h that is ${f(BILLING.total_usd / rate.usd_per_hour, 2)} pod-hours. Pod region ${BILLING.region}.`);

// -- bugs -------------------------------------------------------------------------------------------------------------------
H("Two bugs the run surfaced");
P(`1. **The WebGPU microbench could not run on 7B.** The first six remote runs (kept above) reported \`webgpu false\` although Chrome had an adapter: the runtime's synthetic head weight was built by encoding a random Float32 [vocab, d] array, 2.2 GB for 7B, and the allocation failed inside the SDK's try/catch, so the planner saw no browser side. Fixed by writing random q8/q4 bytes straight into the entry layout (commit \`fa52970\`); the SDK now logs the failure and \`measure-remote.mjs\` refuses to measure without WebGPU.
2. **The bandwidth probe measured time to first byte.** It timed a 1 MiB read from the start of the fetch, so on a ~160 ms link it reported about 2 MB/s while loads ran at 20 MB/s. It now starts the clock at the first byte and reads the whole chunk (commit \`b71943d\`); the remote tables above show the probe after the fix.`);

writeFileSync(join(repo, "docs/phase-7-notes.md"), out.join("\n").replace(/\n{3,}/g, "\n\n"));
console.log("wrote docs/phase-7-notes.md");
