"""The 200 tokenizer test strings for Phase 5a's TypeScript tokenizer (gate 1).

Categories: the fixture prompt, wiki-style sentences, code, emoji, CJK and other
scripts, whitespace edge cases, and mixed punctuation/numbers/contractions. The
list is fixed here so the fixture is reproducible; `cases()` asserts 200.
"""

from __future__ import annotations

from .fixtures import FIXTURE_PROMPT

WIKI = [
    "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
    "Photosynthesis converts light energy into chemical energy stored in glucose.",
    "In 1969, Apollo 11 landed the first humans on the Moon.",
    "The Amazon River is the largest river by discharge volume of water in the world.",
    "Ludwig van Beethoven composed his Ninth Symphony while almost completely deaf.",
    "Quantum mechanics describes the behaviour of matter at atomic and subatomic scales.",
    "The Great Barrier Reef stretches over 2,300 kilometres off the coast of Queensland.",
    "Marie Curie was the first person to win Nobel Prizes in two different sciences.",
    "A haiku is a short form of Japanese poetry with a 5-7-5 syllable structure.",
    "The printing press, invented by Johannes Gutenberg around 1440, transformed Europe.",
    "Mount Everest's summit is 8,848.86 metres above sea level according to a 2020 survey.",
    "The mitochondrion is often called the powerhouse of the cell.",
    "Shakespeare's Hamlet was probably written between 1599 and 1601.",
    "The Treaty of Westphalia (1648) ended the Thirty Years' War.",
    "Honey never spoils; edible honey has been found in ancient Egyptian tombs.",
    "The speed of light in vacuum is exactly 299,792,458 metres per second.",
    "Octopuses have three hearts and blue, copper-based blood.",
    "The Rosetta Stone was key to deciphering Egyptian hieroglyphs.",
    "Antarctica is the driest, windiest and coldest continent on Earth.",
    "The human genome contains approximately 3 billion base pairs.",
    "Bach's Well-Tempered Clavier explores all 24 major and minor keys.",
    "The Dead Sea's surface is about 430 metres below sea level.",
    "Pluto was reclassified as a dwarf planet by the IAU in 2006.",
    "The Silk Road connected China with the Mediterranean for centuries.",
    "Ada Lovelace is often regarded as the first computer programmer.",
    "Venus rotates in the opposite direction to most planets in the Solar System.",
    "The Battle of Hastings took place on 14 October 1066.",
    "Coral bleaching occurs when stressed corals expel their symbiotic algae.",
    "Tokyo is the most populous metropolitan area in the world.",
    "The Fibonacci sequence appears in sunflower seed heads and pine cones.",
    "Vaccination against smallpox led to its global eradication in 1980.",
    "Ozone in the stratosphere absorbs most of the Sun's ultraviolet radiation.",
    "The Louvre was originally built as a fortress in the late 12th century.",
    "Dolphins sleep with one half of their brain at a time.",
    "Jupiter's Great Red Spot is a storm larger than Earth.",
    "The Magna Carta was sealed by King John at Runnymede in 1215.",
    "Iceland is one of the few places where you can see the Mid-Atlantic Ridge on land.",
    "Alan Turing's 1936 paper introduced the concept of a universal machine.",
    "Chess originated in India around the 6th century as chaturanga.",
    "The Sahara is roughly the size of the United States.",
]

CODE = [
    "def fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\n",
    "for (let i = 0; i < 10; i++) { console.log(i); }",
    "SELECT id, name FROM users WHERE age >= 18 ORDER BY name;",
    "#include <stdio.h>\nint main(void) { printf(\"hello\\n\"); return 0; }\n",
    "const x = arr.map((v) => v * 2).filter(Boolean);",
    "if __name__ == \"__main__\":\n    main()\n",
    "fn main() { let v: Vec<u32> = (0..10).collect(); println!(\"{:?}\", v); }",
    "import numpy as np\nx = np.zeros((3, 4), dtype=np.float16)\n",
    "git commit -m \"fix: handle empty input\" && git push origin main",
    "<div class=\"container\"><p id=\"x\">Hello &amp; welcome</p></div>",
    "{\"key\": \"value\", \"n\": 42, \"list\": [1, 2, 3], \"ok\": true}",
    "x = a ** 2 + b ** 2; y = math.sqrt(x)  # hypotenuse",
    "@group(0) @binding(0) var<storage, read> w: array<u32>;",
    "let mut total = 0u64;\nfor i in 0..n { total += i as u64; }",
    "SELECT COUNT(*) FROM t GROUP BY k HAVING COUNT(*) > 1;",
    "public static void main(String[] args) { System.out.println(\"hi\"); }",
    "    \tindented with tab and spaces\n\t\tdouble tab",
    "async function load() {\n  const r = await fetch(url);\n  return r.json();\n}\n",
    "print(f\"{value:.3f} {name!r} {n:>8d}\")",
    "s/foo/bar/g; s#a/b#c/d#",
    "0x1F600 0b1010 0o777 1e-5 3.14159 -42 +7",
    "a->b->c; ptr->next = NULL; *p++ = *q++;",
    "lambda x, y=2, *args, **kw: (x, y, args, kw)",
    "match v {\n    Some(x) if x > 0 => x,\n    _ => 0,\n}",
    "CREATE TABLE t (id INTEGER PRIMARY KEY, v REAL NOT NULL);",
    "std::vector<std::pair<int, std::string>> items;",
    "x <<= 3; y >>= 1; z ^= 0xFF; w |= 1 << 4; q &= ~mask;",
    "#!/bin/bash\nset -euo pipefail\nfor f in *.txt; do echo \"$f\"; done\n",
    "regex = re.compile(r\"^(\\d{4})-(\\d{2})-(\\d{2})$\")",
    "R\"(raw string with \"quotes\" and \\backslashes)\"",
]

EMOJI = [
    "I love pizza 🍕 and tacos 🌮!",
    "😀😃😄😁😆😅😂🤣",
    "Thumbs up 👍🏽 and 👍🏿 with skin tones",
    "Family: 👨‍👩‍👧‍👦 and flags 🇬🇧🇯🇵🇧🇷",
    "Rocket 🚀 to the moon 🌙✨",
    "❤️ 💙 💚 💛 🧡 💜 🖤 🤍",
    "Combining: é (e + ◌́) vs precomposed é",
    "Zero-width joiner 👩‍💻 and variation selector ☺️",
    "🎉 Congratulations!!! 🎊🎈",
    "Weather: ☀️🌤️⛅🌧️⛈️❄️",
    "→ ← ↑ ↓ ↔ ⇒ ⇔ ∞ ≈ ≠ ≤ ≥ ± × ÷",
    "Chess ♔♕♖♗♘♙ and cards ♠♥♦♣",
    "Music 🎵🎶 notes ♩♪♫♬",
    "🧑‍🚀🧑‍🔬🧑‍🎨 professions",
    "Keycaps 1️⃣2️⃣3️⃣ and #️⃣*️⃣",
    "Mixed 😀 text 中文 and code `x = 1`",
    "🏳️‍🌈 🏴‍☠️ 🏁",
    "Bullets • ◦ ▪ ▫ and box ┌─┐│└┘",
    "Currency € £ ¥ ₹ ₽ ₩ ¢ $",
    "Fractions ½ ⅓ ¼ ¾ and superscripts x² y³ eⁿ",
]

CJK = [
    "日本語のテキストをトークン化する。",
    "东京是日本的首都，也是世界上人口最多的都市圈。",
    "東京は日本の首都であり、世界最大の都市圏です。",
    "한국어 문장을 토큰으로 나눕니다.",
    "中文和English混合的句子。",
    "漢字、ひらがな、カタカナ、ＡＢＣ（全角）",
    "我喜欢吃苹果和香蕉。你呢？",
    "これはペンです。あれは本です。",
    "안녕하세요! 만나서 반갑습니다.",
    "北京、上海、广州、深圳是中国的四个一线城市。",
    "Привет, мир! Это тест на русском языке.",
    "Ελληνικά: Καλημέρα κόσμε.",
    "العربية: مرحبا بالعالم.",
    "עברית: שלום עולם.",
    "हिन्दी: नमस्ते दुनिया।",
    "ไทย: สวัสดีชาวโลก",
    "Tiếng Việt: Xin chào thế giới.",
    "Türkçe: Merhaba dünya, İstanbul'da güneşli bir gün.",
    "Deutsch: Straße, Größe, Übermaß, ähnlich.",
    "Français: où est la bibliothèque ? Ça va très bien.",
    "Español: ¿Cómo estás? ¡Muy bien, gracias!",
    "Português: São Paulo é uma cidade enorme.",
    "Polski: Zażółć gęślą jaźń.",
    "Čeština: Příliš žluťoučký kůň úpěl ďábelské ódy.",
    "繁體中文：臺灣的夜市非常有名。",
    "簡体字と繁体字：学/學、国/國、体/體",
    "ㄅㄆㄇㄈ 注音符號",
    "𠮷野家 (CJK Extension B) and 🈶🈚",
    "全角スペース　と半角スペース の違い",
    "「こんにちは」と『さようなら』、【重要】",
]

WHITESPACE = [
    "",
    " ",
    "  ",
    "   ",
    "\n",
    "\n\n",
    "\r\n",
    "\t",
    "\t\t",
    " \n",
    "\n ",
    " leading space",
    "trailing space ",
    "  two leading",
    "two trailing  ",
    "multiple   internal   spaces",
    "line1\nline2\nline3",
    "line1\r\nline2\r\n",
    "\n\nparagraph after blank lines",
    "tab\tseparated\tvalues",
    "space then tab \tmix",
    "  \n  \n  ",
    "no-break\u00a0space",
    "ideographic\u3000space",
    "zero\u200bwidth\u200bspace",
    "form\ffeed and vertical\vtab",
    "ends with newline\n",
    "ends with two newlines\n\n",
    "    four-space indent\n        eight-space indent",
    "\t\n\t\n",
    "word \n word",
    "a\n\n\n\nb",
    " \t \t ",
    "x                                y",
    "\u2028line separator\u2029paragraph separator",
]

MIXED = [
    "I'm sure they're going to say it's fine, but we've seen he'd rather not.",
    "I'M SURE THEY'RE GOING TO SAY IT'S FINE.",
    "Don't. Won't. Can't. Shan't. Y'all. O'Neil. Rock'n'roll.",
    "Prices rose 3.5% to $1,234.56 (up from $1,192.00) in Q3 2024.",
    "Call +1 (555) 010-2030 or email test.user+tag@example.co.uk today!",
    "Visit https://example.com/path?query=1&other=two#fragment now.",
    "1234567890 0987654321 1 12 123 1234 12345 123456",
    "3.14159265358979323846264338327950288419716939937510",
    "The year 1999 vs 2000 vs 20000 vs 200000 vs 2000000.",
    "Mr. Smith, Dr. Jones & Mrs. O'Brien met at 5:30 p.m.",
    "\"Quoted text,\" she said, \"with 'nested' quotes.\"",
    "Ellipsis... and dashes -- en–dash em—dash",
    "Parentheses (like this), [brackets], {braces}, <angles>",
    "Semicolons; colons: commas, periods. Exclamation! Question?",
    "snake_case camelCase PascalCase kebab-case SCREAMING_SNAKE",
    "file.tar.gz archive.zip image.png document.pdf",
    "C:\\Users\\name\\Documents\\file.txt and /usr/local/bin",
    "a=1;b=2;c=a+b;print(c)",
    "ALL CAPS SENTENCE WITH NUMBERS 42 AND SYMBOLS #@!",
    "MiXeD cAsE wOrDs ArE tOkEnIzEd DiFfErEnTlY",
    "Repeated!!!!!!!!!! punctuation?????????? and ..........",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "abababababababababababababababababab",
    "supercalifragilisticexpialidocious antidisestablishmentarianism",
    "The 1st, 2nd, 3rd, 4th, 21st, 22nd, 23rd, 100th",
    "£100 €200 ¥300 ₹400 $500 ¢6",
    "50% off! Buy 2 get 1 free* (*terms apply)",
    "<|im_start|>user\nHello<|im_end|>\n<|im_start|>assistant\n",
    "<|endoftext|> in the middle <|endoftext|> of text",
    "Not-a-special <|fake_token|> and <|im_start with no close",
    "naïve café résumé façade jalapeño piñata",
    "Ünïcödé lëttérs wïth dïäcrïtïcs everywhere",
    "ǅ ǈ ǋ titlecase digraphs and ß ẞ sharp s",
    "İstanbul with dotted capital I and ı dotless i",
    "ﬁ ﬂ ligatures and Ⅻ roman numeral",
    "① ② ③ circled and ⑴ ⑵ parenthesized",
    "A single character: x",
    "Two: xy",
    "https://",
    "@user #hashtag $cashtag %percent ^caret &amp; *star",
    "Tabs\tand\tspaces and\nnewlines\r\nmixed\ttogether  now",
    "The quick brown fox jumps over the lazy dog.",
    "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.",
    "the quick brown fox jumps over the lazy dog",
]


def cases() -> list[str]:
    out = [FIXTURE_PROMPT, *WIKI, *CODE, *EMOJI, *CJK, *WHITESPACE, *MIXED]
    assert len(out) == 200, f"tokenizer cases: expected 200, have {len(out)}"
    assert len(set(out)) == 200, "tokenizer cases must be distinct"
    return out
